### PR TITLE
add option to remove QML after project creation

### PR DESCRIPTION
**Pull request by Gustry**
@lucernae This is for you ;-)
I made: 
* Add style, remove style, get style as XML, set default style

```
SERVICE=STYLEMANAGER&
REQUEST=AddStyle&
PROJECT=/destination/project.qgs&
LAYER=myLayerId&
QML=/path/to/style.qml&
NAME=name of my style&
REMOVEQML=true
```

Look the readme. Let me know if you need something else (rename, ...)

BTW, I think we should remove QML, as they are unnecessary, they are already included in the QGIS Project. So I added a new option when we create the QGIS project with MAPCOMPOSITION to remove the QML if wanted.

### CODE REVIEW

**Comment by lucernae** [comment]
Thanks @Gustry . Just a several question from me so I can use it:

1. CMIIW, REMOVEQML means the upload qml files will be deleted, right? Because the content is already in QGIS Project?
2. How can I query a list of style names of a layer? Do I uses WMS GetStyle? Can you also provide the instruction on Readme?

**Comment by Gustry** [comment]
> CMIIW, REMOVEQML means the upload qml files will be deleted, right? Because the content is already in QGIS Project?

Yes. Maybe I should fix that to `DELETEQML`, it's more obvious. Yes, the QML is included in the QGIS project itself.
For now in the `qgis_layer` directory, we have a.shp, a.dbf, a.prj, a.qml. a.qgs, a.shx. The file a.qml is useless because the content is already in the a.qgs. That's why I'm providing you a new link `GetStyle`, it will return the XML string for the QML.
Having the .qml file is nice if you have only one style. But if we start having many .qml floating around in the directory, we don't know which layer they belong to. So I think it's ok to remove these QML, even at project creation. But you need to fix the QML download link.

2. In the GetCapabilities, you can have it, look for `<Style>`: http://geonode.kartoza.com/qgis-server/ogc/tmpwjxpyi?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities Do you want a link giving a list of styles separated by comma?

The GetStyle request is giving the SLD : http://geonode.kartoza.com/qgis-server/ogc/tmpwjxpyi?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetStyle&STYLE=default&LAYER=tmpwjxpyi

**Comment by lucernae** [comment]
> Having the .qml file is nice if you have only one style. But if we start having many .qml floating around in the directory, we don't know which layer they belong to. So I think it's ok to remove these QML, even at project creation. But you need to fix the QML download link.

I don't mind refactoring the QML download link. Less files means less things to worry about 😄. +1 for this feature.

For no.2 

In GetCapabilities, it doesn't provide the style names. The style names will be useful to reference the styles, if I give a list of available styles of a layer to QGIS Client (using Geonode API). The GetCapabilites only shows the qgs project (or will it shows the style name?). For the format, anything can do, as long as I can get a list of style names of a layer, it can be a python list of string for example. Or if it is possible to do that just by using GetCapabilities, I don't mind to use that, but I don't know how (or if it is possible) at the moment.

**Comment by Gustry** [comment]
> I don't mind refactoring the QML download link. Less files means less things to worry about 😄. +1 for this feature.

+1, so you can use the function to remove the QML when you create the qgis project and use the plugin to tell you the QML XML string.

> In GetCapabilities, it doesn't provide the style names. 

Yes, as I said. Look for the `<Style>` node in this GetCapabilities: http://geonode.kartoza.com/qgis-server/ogc/tmpwjxpyi?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities . There is only one style on this layer. But if you have many styles, you will get something like this in the GetCapabilities:
screen shot 2017-07-26 at 11 40 35

In QGIS, it's asking which style you want to use, after the GetCapabilities:
screen shot 2017-07-26 at 11 43 45

**Comment by lucernae** [comment]
Ah I see it now. I only see it on GetStyle.
What is the difference between Name and Title? When I'm using StyleManager request, it is referencing Name, right?

**Comment by Gustry** [comment]
You only see it on `GetStyle` ?? Not `GetCapabilities` ?
GetStyle is used to get the SLD.

I guess it's the same. Use `name` just in case.

**Comment by lucernae** [comment]
> You only see it on GetStyle ?? Not GetCapabilities ?
> GetStyle is used to get the SLD.

I mean on the <GetStyle> tags in GetCapabilites response.
Previously I mistakenly saw <GetStyle> tags, while you are talking about <Style> tags.

Can we merge this? I think this is enough for my current use case (I can start working with this using your branch too).

**Comment by Gustry** [comment]
I'm merging this. Tell me if you need an update from me.
I would like to do a clean API, with JSON for instance for the return. But I don't have time for now, I made the minimal API for you to work on ;-)

**Pull request merged**
